name: aes_project
channels:
  - conda-forge
  - defaults

dependencies:
  # core
  - python=3.10
  - pip

  # numerical stack
  - numpy>=2.2
  - pandas>=2.3
  - scipy>=1.15
  - scikit-learn=1.6.1
  - xgboost=3.0.2

  # PyTorch family
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5

  # NLP
  - spacy=3.8
  - spacy-model-en_core_web_sm=3.8.0     
  - textstat
  - gmpy2

  # HF ecosystem (Conda packages)
  - transformers=4.52.4
  - tokenizers=0.21.1
  - huggingface_hub=0.32.4
  - hf-xet=1.1.3

  # web / utils
  - streamlit=1.45
  - altair>=5.5
  - pydeck>=0.9
  - gitpython
  - tqdm
  - rich
  - requests
  - joblib=1.5.1

  - pip:
    - joblib==1.5.1

