name: aes_project
channels:
  - conda-forge      
  - defaults
dependencies:
  - python=3.10
  - pip             

  - numpy>=2.2
  - pandas>=2.3
  - scipy>=1.15
  - scikit-learn==1.6.1
  - xgboost==1.7.6     

  - pytorch=2.5        
  - torchvision=0.20
  - torchaudio=2.5

  - spacy=3.8
  - textstat
  - gmpy2             

  - streamlit=1.45
  - altair>=5.5
  - pydeck>=0.9

  - gitpython
  - tqdm
  - rich
  - requests

